In [2]:
import numpy as np
import pandas as pd

In [3]:
my_dict = {'Меркурий': 4879, 'Марс': 6779, 'Венера': 12104, 'Земля': 12742,
           'Нептун': 49244, 'Уран': 50724, 'Сатурн': 116460,'Юпитер': 139820}
diameters = pd.Series(my_dict)

diameters.sum()

np.int64(392752)

In [4]:
import pandas as pd
# Диаметр в км, Объём в 10^9 км³, Масса в 10^21 кг
planets_list = [['Меркурий', 4879,  60.83,  330.2], ['Марс',     6779,  163.18,  641.85],
                ['Венера',  12104, 928.43, 4868.5], ['Земля',   12742, 1083.21,  5973.6], 
                ['Нептун',  49244,  62540, 102430], ['Уран',    50724,   68340,   86832],
                ['Сатурн', 116460, 827130, 568460], ['Юпитер', 139820, 1431280, 1898600] ]
planets = pd.DataFrame(planets_list, columns=['Название','Диаметр', 'Объём', 'Масса'])
planets = planets.drop(labels=[0,1,2],axis=0)
planets

  Название  Диаметр       Объём      Масса
3    Земля    12742     1083.21     5973.6
4   Нептун    49244    62540.00   102430.0
5     Уран    50724    68340.00    86832.0
6   Сатурн   116460   827130.00   568460.0
7   Юпитер   139820  1431280.00  1898600.0

In [130]:
planets.loc[3:4]

  Название  Диаметр     Объём     Масса
3    Земля    12742   1083.21    5973.6
4   Нептун    49244  62540.00  102430.0

In [131]:
planets.iloc[0:3]

  Название  Диаметр     Объём     Масса
3    Земля    12742   1083.21    5973.6
4   Нептун    49244  62540.00  102430.0
5     Уран    50724  68340.00   86832.0